#ifndef ENUMS_H
#define ENUMS_H

// This file defines the constants used in relationship queries.
// Do not edit this file.


// Genders
enum class Gender {
  MALE,
  FEMALE,
  ANY
};

// Parent Modifiers
enum class PMod {
  MATERNAL,
  PATERNAL,
  ANY
};

// Sibling Modifiers
enum class SMod {
  FULL,
  HALF,
  ANY
};

#endif
